import heapq
from maze.envs.config import COLS, ROWS

class Agent1:
    """Agent class implementing A* search for the maze environment."""
    
    def __init__(self, model, env):
        self.model = model  # Instance of MazeModel
        self.env = env  # Instance of MazeEnv
        self.path = []  # Store the path generated by A* search
    
    def reset(self):
        """Reset the agent's state and reinitialize the environment and model."""
        self.env.reset()  # Reset environment
        self.model.reset()  # Reset model
        self.path = []  # Clear the path

    def agent_function(self, observation):
        """
        Determine the next action based on the current observation.
        This method implements A* search for finding the path.
        """
        # Update the agent's current position
        current_position = observation["agent_position"]
        
        # If the path is empty, perform A* search to find a path to the goal
        if not self.path:
            walls = [[[cell.walls[direction] for direction in range(4)] for cell in row] for row in self.env.grid]
            self.path = self.astar_search(current_position, walls)  # Pass walls to astar_search
            if not self.path:
                raise Exception("A* search failed to find a path to the goal.")
        
        # Pop the next action from the path and convert to an action index for the environment
        next_position = self.path.pop(0)
        x, y = current_position
        nx, ny = next_position
        
        if ny == y - 1:  # Up
            return 0
        elif nx == x + 1:  # Right
            return 1
        elif ny == y + 1:  # Down
            return 2
        elif nx == x - 1:  # Left
            return 3
        
        return None  # No valid move found

    def astar_search(self, start_position, walls):
        """Perform A* search to find a path to the goal from the start position."""
        start_position = tuple(start_position)  # Convert start position to tuple
        goal_position = (COLS - 1, ROWS - 1)
        frontier = []
        heapq.heappush(frontier, (0, start_position))
        came_from = {start_position: None}
        cost_so_far = {start_position: 0}
        
        while frontier:
            _, current = heapq.heappop(frontier)
            
            if current == goal_position:
                return self.reconstruct_path(came_from, current)
            
            for next_position in self.model.ACTIONS(current, walls):  # Pass walls here
                next_position = tuple(next_position)  # Convert to tuple
                new_cost = cost_so_far[current] + 1  # Step cost is 1
                if next_position not in cost_so_far or new_cost < cost_so_far[next_position]:
                    cost_so_far[next_position] = new_cost
                    priority = new_cost + self.model.HEURISTIC(next_position)
                    heapq.heappush(frontier, (priority, next_position))
                    came_from[next_position] = current
        
        return []  # Return an empty path if no path to the goal is found
    
    def reconstruct_path(self, came_from, current):
        """Reconstruct the path to the goal from the 'came_from' map."""
        path = []
        while current in came_from and came_from[current] is not None:
            path.append(current)
            current = came_from[current]
        path.reverse()  # Reverse the path to start from the initial position
        return path